name: linter
  # run lint flake8
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install dependecies
        run: |
          pip install poetry
          poetry install
      - name: run linter
        run: |
          make lint
